import type { Metadata } from "next";
import "./globals.css";
import SideNav from "../components/SideNav";
import { Nunito_Sans, Oswald } from "next/font/google";
import { ThemeProvider } from "next-themes"; // Import ThemeProvider for theme switching

// Import Nunito Sans for the body text
const nunitoSans = Nunito_Sans({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
	variable: "--font-nunito-sans", // CSS variable to use with Tailwind
});

// Import Oswald for the headline text
const oswald = Oswald({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"], // Select appropriate weights
	variable: "--font-oswald", // CSS variable for headlines
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<link
					href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700&family=Oswald:wght@400;500;600&display=swap"
					rel="stylesheet"
				/>
			</head>
			<body
				className={`${nunitoSans.variable} ${oswald.variable} antialiased`}
			>
				{/* Wrapping the app in ThemeProvider for theme toggling */}
				<ThemeProvider attribute="class" defaultTheme="system">
					<div className="flex min-h-screen">
						{/* Sidebar - Takes up a dynamic space */}
						<SideNav />

						{/* Main content - Flex-grow ensures it fills the remaining space */}
						<main className="flex-grow p-8 bg-white transition-all duration-300 dark:bg-gray-900 dark:text-white">
							{children}
						</main>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
